In [1]:
import numpy as np
import pandas as pd

**GroupBy**

In [2]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [3]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [4]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [5]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [6]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**Aggregation**

**mean median min max count std**

In [9]:
df['Sales'].mean()

np.float64(187.5)

In [10]:
df['Sales'].median()

190.0

In [11]:
df['Sales'].min()

100

In [12]:
df['Sales'].max()

300

In [13]:
df['Sales'].count()

np.int64(8)

In [15]:
df['Sales'].std()

66.06274074155351

In [16]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64